// Unbatched reference renderer: the SAME line's runtime/spine-4.x/spine/SkeletonRenderer.cpp compiled under another class
// name, with batchCommands() replaced by a pass-through that links every command (empty ones included).
// Every slot is passed as an "injection slot" so each command carries its slot index (and alpha-0 regions get
// their 0-index dummy command, which does not change geometry).
#define SkeletonRenderer RefSkeletonRenderer
#include "SpineCompat.h"
#include <vector>
#include <utility>
#include <algorithm>
using namespace spine;

template <class V>
static RenderCommand *batchCommands(BlockAllocator &, V &commands) {
    RenderCommand *root = nullptr, *last = nullptr;
    for (int i = 0; i < (int) commands.size(); i++) {
        RenderCommand *c = commands[i];
        c->next = nullptr;
        if (last) last->next = c; else root = c;
        last = c;
    }
    return root;
}

#include "ref_body.inc"   // generated by build.sh: tree's SkeletonRenderer.cpp with `batchCommands(` definition renamed
#undef SkeletonRenderer

struct RefCmd { int slot; int numIndices; int group; };

static std::pair<RenderCommand *, RenderCommand *> refUnpair(std::pair<RenderCommand *, RenderCommand *> *p) { auto r = *p; delete p; return r; }
static std::pair<RenderCommand *, RenderCommand *> refUnpair(std::pair<RenderCommand *, RenderCommand *> p) { return p; }

void refRender(Skeleton &sk, const std::vector<int> *splitSlots, std::vector<RefCmd> &out) {
    static RefSkeletonRenderer *r = new RefSkeletonRenderer();
    std::vector<int> all;
    for (int i = 0; i < (int) sk.getSlots().size(); i++) all.push_back(i);
    out.clear();
    if (splitSlots) {
        Vector<RenderCommand *> a, b;
        auto p = refUnpair(r->render(sk, all, *splitSlots, a, b));
        for (RenderCommand *c = p.first; c; c = c->next) out.push_back({c->injectionSlotIndex, c->numIndices, 1});
        for (RenderCommand *c = p.second; c; c = c->next) out.push_back({c->injectionSlotIndex, c->numIndices, 2});
        // restore draw order across the two lists: order by the slot's draw-order position
        std::vector<int> pos(sk.getSlots().size(), 0);
        auto &drawOrder = spc::drawOrder(&sk);
        for (int i = 0; i < (int) drawOrder.size(); i++) pos[drawOrder[i]->getData().getIndex()] = i;
        std::stable_sort(out.begin(), out.end(), [&](const RefCmd &x, const RefCmd &y) { return pos[x.slot] < pos[y.slot]; });
    } else {
        for (RenderCommand *c = r->render(sk, all); c; c = c->next) out.push_back({c->injectionSlotIndex, c->numIndices, 1});
    }
}
