#!/usr/bin/env python3
"""Writes the synthetic 4.2 sequence fixture into <out>/: sequence.json, sequence.atlas, its pages sequence.png and
sequence_2.png, and license.txt.

Usage: python3 tests/lifecycle/assets/4.2/sequence/generate.py [out]   (default out: this script's folder)
Pure stdlib. The committed files are this script's output byte for byte; edit the tables below, never the files.

Slot `seq` shows region attachment `seq` with a sequence of len(FRAMES) frames (regions seq01, seq02, ...), each a
FRAME x FRAME block of one plain colour; the first PAGE1_FRAMES frames sit on page 1, the rest on page 2.
Animation `flip` keys the sequence (loop, DELAY per frame) and rotates the slot's bone, so it lasts DURATION seconds.
"""
import json
import struct
import sys
import zlib
from pathlib import Path

FRAMES = [(255, 0, 0), (255, 128, 0), (255, 255, 0), (0, 255, 0), (0, 255, 255), (0, 0, 255), (128, 0, 255),
          (255, 0, 255), (128, 128, 128)]
PAGE1_FRAMES = 5
FRAME = 32
DIGITS = 2
DELAY = 0.1
DURATION = 1
VERSION = "4.2.22"
PAGES = ["sequence.png", "sequence_2.png"]
LICENSE = """Test-only fixture generated by generate.py in this folder: plain-colour frames, no third-party art.
Released under the MIT licence of this repository (LICENSE at the repository root).
"""


def png(colors):
    w = FRAME * len(colors)
    row = b"\0" + b"".join(bytes(c + (255,)) * FRAME for c in colors)

    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xffffffff)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, FRAME, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(row * FRAME, 9)) + chunk(b"IEND", b""))


def pages():
    return [(PAGES[0], FRAMES[:PAGE1_FRAMES], 1), (PAGES[1], FRAMES[PAGE1_FRAMES:], PAGE1_FRAMES + 1)]


def atlas():
    out = []
    for name, colors, first in pages():
        regions = "".join("seq%0*d\n\tbounds: %d, 0, %d, %d\n" % (DIGITS, first + i, i * FRAME, FRAME, FRAME)
                          for i in range(len(colors)))
        out.append("%s\n\tsize: %d, %d\n\tfilter: Linear, Linear\n%s" % (name, FRAME * len(colors), FRAME, regions))
    return "\n".join(out)


def skeleton():
    return {
        "skeleton": {"hash": "sequence", "spine": VERSION, "x": -FRAME // 2, "y": -FRAME // 2, "width": FRAME,
                     "height": FRAME},
        "bones": [{"name": "root"}, {"name": "b_seq", "parent": "root"}],
        "slots": [{"name": "seq", "bone": "b_seq", "attachment": "seq"}],
        "skins": [{"name": "default", "attachments": {"seq": {"seq": {
            "width": FRAME, "height": FRAME, "sequence": {"count": len(FRAMES), "digits": DIGITS}}}}}],
        "animations": {"flip": {
            "bones": {"b_seq": {"rotate": [{"time": 0}, {"time": DURATION, "value": 90}]}},
            "attachments": {"default": {"seq": {"seq": {"sequence": [{"mode": "loop", "delay": DELAY}]}}}},
        }},
    }


def main(out):
    out.mkdir(parents=True, exist_ok=True)
    (out / "sequence.json").write_text(json.dumps(skeleton(), indent=1) + "\n")
    (out / "sequence.atlas").write_text(atlas())
    for name, colors, _ in pages():
        (out / name).write_bytes(png(colors))
    (out / "license.txt").write_text(LICENSE)


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent)
