// Y-flip correctness matrix for the checkout's spine-cpp physics and IK (gap-4), on the runtime line build.sh compiles.
// Links the checkout's runtime and compares, per frame and per bone, the world state of
//   A: the plugin's configuration, read from the checkout by build.sh (plugin_config.cpp; 1.5.0 is
//      skeleton scaleY=-1, Bone::yDown=false, shared/Lua_Spine.cpp:198)
//   B: skeleton scaleY=+1, Bone::yDown=true    (upstream y-down integrations, 4.3 default)
// with the mirror of the y-up reference
//   R: skeleton scaleY=+1, Bone::yDown=false
// mirror(R): worldX, -worldY, a, b, -c, -d. User actions are given in screen space (y down):
// A/B apply them as is, R applies the mirrored action (y -> -y, degrees -> -degrees).
// After its table, each mode prints one check row per case, "PASS|FAIL<TAB><test id>": a case passes when A and B
// both match mirror(R).
#include "SpineCompat.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>

using namespace spine;

SpineExtension *spine::getDefaultExtension() { return new DefaultSpineExtension(); }
struct StubLoader : public TextureLoader {
    void load(AtlasPage &page, const String &) override { page.texture = (void *)0x1; }
    void unload(void *) override {}
};
static StubLoader g_loader;
extern const float kPluginScaleY;  // plugin_config.cpp, generated by build.sh
extern const bool kPluginYDown;

enum Cfg { CR = 0, CA = 1, CB = 2 };
static const char *cfgName[] = {"R", "A", "B"};
// Line differences of the model reads below (the plugin's spc:: seam covers the rest)
#if SPINE_43()
static Bone *physicsBone(PhysicsConstraint &c) { return spc::boneOf(&c.getBone()); }
static BoneData &physicsBone(PhysicsConstraintData &d) { return d.getBone(); }
static BoneData &ikTarget(ConstraintData *d) { return static_cast<IkConstraintData *>(d)->getTarget(); }
template <class F> static void forEachPhysicsData(SkeletonData *d, F f) {
    Array<ConstraintData *> &c = d->getConstraints();
    for (size_t i = 0; i < c.size(); ++i)
        if (c[i]->getRTTI().instanceOf(PhysicsConstraintData::rtti)) f(static_cast<PhysicsConstraintData *>(c[i]));
}
#else
static Bone *physicsBone(PhysicsConstraint &c) { return c.getBone(); }
static BoneData &physicsBone(PhysicsConstraintData &d) { return *d.getBone(); }
static BoneData &ikTarget(IkConstraintData *d) { return *d->getTarget(); }
template <class F> static void forEachPhysicsData(SkeletonData *d, F f) {
    Vector<PhysicsConstraintData *> &c = d->getPhysicsConstraints();
    for (size_t i = 0; i < c.size(); ++i) f(c[i]);
}
#endif
// One skeleton with its own animation state, freed on scope exit
struct Rig {
    std::unique_ptr<Skeleton> sk;
    std::unique_ptr<AnimationStateData> sd;
    std::unique_ptr<AnimationState> st;
    explicit Rig(SkeletonData *data)
        : sk(spc::newSkeleton(data)), sd(spc::newStateData(data)), st(spc::newState(sd.get())) {}
};

static void applyCfg(Skeleton &sk, Cfg c) {
    Bone::setYDown(c == CB || (c == CA && kPluginYDown));
    sk.setScaleX(1);
    sk.setScaleY(c == CA ? kPluginScaleY : 1);
}
// screen-space (y-down) value -> this configuration's world value
static float wy(Cfg c, float v) { return c == CR ? -v : v; }
static float wdeg(Cfg c, float d) { return c == CR ? -d : d; }

struct Loaded { Atlas *atlas; SkeletonData *data; std::string name; };
static std::map<std::string, Atlas *> g_atlases;
static Loaded load(const std::string &name, const std::string &atlasName, const std::string &jsonPath) {
    std::string a = atlasName + "/" + atlasName + ".atlas";
    Atlas *atlas = g_atlases[a];
    if (!atlas) atlas = g_atlases[a] = new Atlas(a.c_str(), &g_loader, true);
    std::unique_ptr<SkeletonJson> json(spc::newJson(atlas));
    SkeletonData *data = json->readSkeletonDataFile(jsonPath.c_str());
    if (!data) { std::fprintf(stderr, "load failed %s: %s\n", jsonPath.c_str(), json->getError().buffer()); std::exit(1); }
    return {atlas, data, name};
}

typedef std::vector<float> Frame;  // 6 floats per bone: x y a b c d
struct Run { std::vector<Frame> frames; };

static void snap(Skeleton &sk, Run &run) {
    Frame f;
    auto &bones = sk.getBones();
    f.reserve(bones.size() * 6);
    for (size_t i = 0; i < bones.size(); ++i) {
        auto &b = spc::applied(*bones[i]);
        f.push_back(b.getWorldX()); f.push_back(b.getWorldY());
        f.push_back(b.getA()); f.push_back(b.getB()); f.push_back(b.getC()); f.push_back(b.getD());
        if (!bones[i]->isActive()) f[i * 6] = NAN;  // skin-required bone not in the current skin: never updated, skip
    }
    run.frames.push_back(f);
}

struct Scenario {
    std::string name;
    int frames = 120;
    std::function<void(Skeleton &, AnimationState &, Cfg)> setup;                 // after setup pose, before first frame
    std::function<void(Skeleton &, AnimationState &, Cfg, int)> pre;               // before each frame's update
    std::function<void(Skeleton &, AnimationState &, Cfg, int)> post;              // after UWT; if set, UWT(Physics_Pose) again
};

static Run simulate(SkeletonData *data, Cfg c, const Scenario &sc) {
    Run run;
    Rig rig(data);
    Skeleton &sk = *rig.sk;
    AnimationState &st = *rig.st;
    applyCfg(sk, c);
    spc::setToSetupPose(&sk);
    if (sc.setup) sc.setup(sk, st, c);
    sk.updateWorldTransform(Physics_Reset);
    const float dt = 1.0f / 60.0f;
    for (int f = 0; f < sc.frames; ++f) {
        if (sc.pre) sc.pre(sk, st, c, f);
        st.update(dt);
        st.apply(sk);
        sk.update(dt);
        sk.updateWorldTransform(Physics_Update);
        if (sc.post) { sc.post(sk, st, c, f); sk.updateWorldTransform(Physics_Pose); }
        snap(sk, run);
    }
    Bone::setYDown(false);
    return run;
}

struct Dev {
    double pos = 0, rot = 0, mat = 0;
    std::string posBone, matBone; int posFrame = -1, matFrame = -1;
    void merge(const Dev &o) {
        if (o.pos > pos) { pos = o.pos; posBone = o.posBone; posFrame = o.posFrame; }
        if (o.rot > rot) rot = o.rot;
        if (o.mat > mat) { mat = o.mat; matBone = o.matBone; matFrame = o.matFrame; }
    }
};
static double angDiff(double a, double b) {
    double d = std::fmod(a - b, 360.0);
    if (d > 180) d -= 360;
    if (d < -180) d += 360;
    return std::fabs(d);
}
static const double R2D = 57.29577951308232;
// compare test run T with mirror of reference run Rr, restricted to bone mask (empty = all)
static Dev compare(const Run &Rr, const Run &T, SkeletonData *data, const std::vector<bool> &mask) {
    Dev d;
    auto &bones = data->getBones();
    for (size_t f = 0; f < Rr.frames.size(); ++f) {
        const Frame &r = Rr.frames[f], &t = T.frames[f];
        for (size_t i = 0; i < bones.size(); ++i) {
            if (!mask.empty() && !mask[i]) continue;
            const float *R = &r[i * 6], *X = &t[i * 6];
            if (std::isnan(R[0]) || std::isnan(X[0])) continue;
            double mx = R[0], my = -R[1], ma = R[2], mb = R[3], mc = -R[4], md = -R[5];
            double p = std::hypot(X[0] - mx, X[1] - my);
            if (p > d.pos) { d.pos = p; d.posBone = bones[i]->getName().buffer(); d.posFrame = (int)f; }
            double m = std::max(std::max(std::fabs(X[2] - ma), std::fabs(X[3] - mb)), std::max(std::fabs(X[4] - mc), std::fabs(X[5] - md)));
            if (m > d.mat) { d.mat = m; d.matBone = bones[i]->getName().buffer(); d.matFrame = (int)f;
                if (getenv("YFLIP_DEBUG")) std::fprintf(stderr, "mat dev %s f%zu: test a=%g b=%g c=%g d=%g mirrorR a=%g b=%g c=%g d=%g\n", d.matBone.c_str(), f, X[2], X[3], X[4], X[5], ma, mb, mc, md); }
            if (std::hypot(ma, mc) > 1e-3 && std::hypot(X[2], X[4]) > 1e-3) {
                double rr = angDiff(std::atan2(X[4], X[2]) * R2D, std::atan2(mc, ma) * R2D);
                if (rr > d.rot) d.rot = rr;
            }
            if (std::hypot(mb, md) > 1e-3 && std::hypot(X[3], X[5]) > 1e-3) {
                double rr = angDiff(std::atan2(X[5], X[3]) * R2D, std::atan2(md, mb) * R2D);
                if (rr > d.rot) d.rot = rr;
            }
        }
    }
    return d;
}

// ---- bone groups by physics property mix ----
static std::string physGroup(PhysicsConstraintData *pd) {
    std::string g;
    if (pd->getX() > 0 || pd->getY() > 0) g += "xy+";
    if (pd->getRotate() > 0) g += "rotate+";
    if (pd->getShearX() > 0) g += "shearX+";
    if (pd->getScaleX() > 0) g += "scaleX+";
    if (!g.empty()) g.pop_back();
    return g;
}
static std::map<std::string, std::vector<bool>> groupMasks(SkeletonData *data) {
    std::map<std::string, std::vector<bool>> m;
    size_t nb = data->getBones().size();
    forEachPhysicsData(data, [&](PhysicsConstraintData *pd) {
        auto &v = m[physGroup(pd)];
        if (v.empty()) v.assign(nb, false);
        v[physicsBone(*pd).getIndex()] = true;
    });
    return m;
}

static Run mirrorRun(const Run &r) {
    Run m = r;
    for (auto &f : m.frames)
        for (size_t i = 0; i < f.size(); i += 6) { f[i + 1] = -f[i + 1]; f[i + 4] = -f[i + 4]; f[i + 5] = -f[i + 5]; }
    return m;
}
static FILE *g_detail;
static std::string g_variant;
static void check(bool ok, const std::string &id) { std::printf("%s\t%s\n", ok ? "PASS" : "FAIL", id.c_str()); }
static bool exact(const Dev &d) { return d.pos < 1e-3 && d.rot < 1e-3; }
struct Row { std::string skel, cas; Dev A, B, AB; std::map<std::string, std::pair<Dev, Dev>> groups; };
static std::vector<Row> g_rows;

static void runCase(Loaded &L, const Scenario &sc, bool groups) {
    Run r = simulate(L.data, CR, sc), a = simulate(L.data, CA, sc), b = simulate(L.data, CB, sc);
    Row row; row.skel = L.name; row.cas = sc.name;
    std::vector<bool> all;
    row.A = compare(r, a, L.data, all);
    row.B = compare(r, b, L.data, all);
    row.AB = compare(mirrorRun(b), a, L.data, all);  // A vs B directly, same (y-down) world
    if (groups)
        for (auto &kv : groupMasks(L.data)) row.groups[kv.first] = {compare(r, a, L.data, kv.second), compare(r, b, L.data, kv.second)};
    // B vs A directly (same world): used to show Lua-visible equality
    std::fprintf(g_detail, "%s %-16s %-34s A: pos=%9.4f rot=%8.4f mat=%8.5f (%s@%d mat:%s) | B: pos=%9.4f rot=%8.4f mat=%8.5f (%s@%d) | A-vs-B: pos=%9.4f rot=%8.4f (%s@%d)\n",
                 g_variant.c_str(), L.name.c_str(), sc.name.c_str(), row.A.pos, row.A.rot, row.A.mat, row.A.posBone.c_str(), row.A.posFrame, row.A.matBone.c_str(),
                 row.B.pos, row.B.rot, row.B.mat, row.B.posBone.c_str(), row.B.posFrame, row.AB.pos, row.AB.rot, row.AB.posBone.c_str(), row.AB.posFrame);
    for (auto &kv : row.groups)
        std::fprintf(g_detail, "%s %-16s %-34s   group %-22s A: pos=%9.4f rot=%8.4f | B: pos=%9.4f rot=%8.4f\n", g_variant.c_str(), L.name.c_str(),
                     sc.name.c_str(), kv.first.c_str(), kv.second.first.pos, kv.second.first.rot, kv.second.second.pos, kv.second.second.rot);
    std::fprintf(g_detail, "%s %-16s %-34s   exact: A.pos=%.3g A.mat=%.3g B.pos=%.3g B.mat=%.3g AB.pos=%.3g AB.mat=%.3g\n", g_variant.c_str(), L.name.c_str(), sc.name.c_str(),
                 row.A.pos, row.A.mat, row.B.pos, row.B.mat, row.AB.pos, row.AB.mat);
    g_rows.push_back(row);
}

// ---- IK target move helpers ----
struct Saved { Bone *b; float x, y; };
static void moveTargets(Skeleton &sk, Cfg c, const std::vector<std::string> &names, std::vector<Saved> &saved) {
    saved.clear();
    for (auto &n : names) {
        Bone *t = sk.findBone(n.c_str());
        if (!t) { std::fprintf(stderr, "no bone %s\n", n.c_str()); std::exit(1); }
        saved.push_back({t, spc::pose(*t).getX(), spc::pose(*t).getY()});
    }
    // compute all new locals from the un-moved world state first
    std::vector<std::pair<float, float>> locals;
    for (auto &s : saved) {
        Bone *t = s.b, *p = t->getParent();
        float nx = spc::applied(*t).getWorldX() + 20, ny = spc::applied(*t).getWorldY() + wy(c, 20), lx, ly;
        if (p) spc::applied(*p).worldToLocal(nx, ny, lx, ly);
        else { lx = spc::pose(*t).getX() + 20 / sk.getScaleX(); ly = spc::pose(*t).getY() + wy(c, 20) / sk.getScaleY(); }  // root bone
        locals.push_back({lx, ly});
    }
    for (size_t i = 0; i < saved.size(); ++i) { spc::pose(*saved[i].b).setX(locals[i].first); spc::pose(*saved[i].b).setY(locals[i].second); }
}
static void restoreTargets(std::vector<Saved> &saved) {
    for (auto &s : saved) { spc::pose(*s.b).setX(s.x); spc::pose(*s.b).setY(s.y); }
    saved.clear();
}
static std::vector<std::string> ikTargets(SkeletonData *d) {
    std::vector<std::string> v;
    spc::forEachIkData(d, [&](auto *ik) {
        std::string n = ikTarget(ik).getName().buffer();
        bool dup = false;
        for (auto &x : v) dup |= x == n;
        if (!dup) v.push_back(n);
    });
    return v;
}
static Scenario ikScenario(const std::string &name, const std::vector<std::string> &targets, std::vector<std::pair<int, std::string>> anims, int frames) {
    auto saved = std::make_shared<std::vector<Saved>>();
    Scenario sc; sc.name = name; sc.frames = frames;
    sc.setup = [anims, saved](Skeleton &sk, AnimationState &st, Cfg) {
        saved->clear();  // bones saved by the previous run belong to a destroyed skeleton
        for (auto &a : anims) st.setAnimation(a.first, a.second.c_str(), true);
    };
    sc.pre = [saved](Skeleton &, AnimationState &, Cfg, int) { restoreTargets(*saved); };
    sc.post = [saved, targets](Skeleton &sk, AnimationState &, Cfg c, int) { moveTargets(sk, c, targets, *saved); };
    return sc;
}

static void physicsSuite(Loaded &L) {
    auto &anims = L.data->getAnimations();
    Dev worstA, worstB;
    for (size_t i = 0; i < anims.size(); ++i) {
        Scenario sc; sc.name = std::string("1 anim:") + anims[i]->getName().buffer();
        std::string an = anims[i]->getName().buffer();
        sc.setup = [an](Skeleton &, AnimationState &st, Cfg) { st.setAnimation(0, an.c_str(), true); };
        runCase(L, sc, true);
    }
    {
        Scenario sc; sc.name = "2 idle translate(60,0),(0,60)"; sc.frames = 130;
        sc.pre = [](Skeleton &sk, AnimationState &, Cfg c, int f) {
            if (f == 10) sk.physicsTranslate(60, 0);
            if (f == 70) sk.physicsTranslate(0, wy(c, 60));
        };
        runCase(L, sc, true);
    }
    {
        Scenario sc; sc.name = "3 idle rotate(root,+30deg)"; sc.frames = 120;
        sc.pre = [](Skeleton &sk, AnimationState &, Cfg c, int f) {
            if (f == 10) { auto &r = spc::applied(*sk.getRootBone()); sk.physicsRotate(r.getWorldX(), r.getWorldY(), wdeg(c, 30)); }
        };
        runCase(L, sc, true);
    }
    {
        Scenario sc; sc.name = "4 idle wind=25 (all constraints)";
        sc.setup = [](Skeleton &sk, AnimationState &, Cfg) { auto &p = sk.getPhysicsConstraints(); for (size_t i = 0; i < p.size(); ++i) spc::pose(*p[i]).setWind(25); };
        runCase(L, sc, true);
    }
    {
        Scenario sc; sc.name = "5 idle gravity=50 (all constraints)";
        sc.setup = [](Skeleton &sk, AnimationState &, Cfg) { auto &p = sk.getPhysicsConstraints(); for (size_t i = 0; i < p.size(); ++i) spc::pose(*p[i]).setGravity(50); };
        runCase(L, sc, true);
    }
    {
        Scenario sc; sc.name = "5b anim0 + wind25 + gravity50 + translate"; sc.frames = 130;
        std::string an = anims.size() ? anims[0]->getName().buffer() : "";
        sc.setup = [an](Skeleton &sk, AnimationState &st, Cfg) {
            if (!an.empty()) st.setAnimation(0, an.c_str(), true);
            auto &p = sk.getPhysicsConstraints(); for (size_t i = 0; i < p.size(); ++i) { spc::pose(*p[i]).setWind(25); spc::pose(*p[i]).setGravity(50); }
        };
        sc.pre = [](Skeleton &sk, AnimationState &, Cfg c, int f) {
            // (animations that key wind override the forced value while they are keyed)
            if (f == 10) sk.physicsTranslate(60, 0);
            if (f == 70) sk.physicsTranslate(0, wy(c, 60));
        };
        runCase(L, sc, true);
    }
}

// direction probe: where does a physics bone go on screen under gravity (mean screen-y displacement of xy bones)
static void directionProbe(Loaded &L, FILE *out) {
    for (int ci = 0; ci < 3; ++ci) {
        Cfg c = (Cfg)ci;
        Rig rig(L.data);
        Skeleton &sk = *rig.sk; applyCfg(sk, c); spc::setToSetupPose(&sk);
        auto &p = sk.getPhysicsConstraints();
        for (size_t i = 0; i < p.size(); ++i) spc::pose(*p[i]).setGravity(50);
        sk.updateWorldTransform(Physics_Reset);
        // pick first rotate-only constraint bone and first xy constraint bone
        Bone *rotBone = nullptr, *xyBone = nullptr;
        for (size_t i = 0; i < p.size(); ++i) {
            auto &d = p[i]->getData();
            Bone *b = physicsBone(*p[i]);
            if (!rotBone && d.getRotate() > 0 && d.getX() == 0 && d.getY() == 0 && b->getData().getLength() > 0) rotBone = b;
            if (!xyBone && d.getY() > 0 && d.getRotate() == 0) xyBone = b;
        }
        float r0 = rotBone ? spc::applied(*rotBone).getWorldRotationX() : 0, y0 = xyBone ? spc::applied(*xyBone).getWorldY() : 0;
        float tipY0 = 0;
        if (rotBone) { float tx, ty; spc::applied(*rotBone).localToWorld(rotBone->getData().getLength(), 0, tx, ty); tipY0 = ty - spc::applied(*rotBone).getWorldY(); }
        for (int f = 0; f < 60; ++f) { sk.update(1 / 60.f); sk.updateWorldTransform(Physics_Update); }
        float screenSign = (c == CR) ? -1 : 1;  // world y -> screen-down
        if (rotBone) {
            float tx, ty; spc::applied(*rotBone).localToWorld(rotBone->getData().getLength(), 0, tx, ty);
            float tipY1 = ty - spc::applied(*rotBone).getWorldY();
            std::fprintf(out, "%s %-16s cfg %s gravity=50: rotate bone %-22s tip relative screen-y %8.2f -> %8.2f (%s on screen)\n", g_variant.c_str(), L.name.c_str(), cfgName[c],
                         rotBone->getData().getName().buffer(), tipY0 * screenSign, tipY1 * screenSign, (tipY1 - tipY0) * screenSign > 0 ? "tip swings DOWN" : "tip swings UP");
        }
        if (xyBone) {
            float y1 = spc::applied(*xyBone).getWorldY();
            std::fprintf(out, "%s %-16s cfg %s gravity=50: xy bone %-26s screen-dy %8.2f (%s)\n", g_variant.c_str(), L.name.c_str(), cfgName[c],
                         xyBone->getData().getName().buffer(), (y1 - y0) * screenSign, (y1 - y0) * screenSign > 0 ? "falls DOWN" : "rises UP");
        }
        (void)r0;
    }
    Bone::setYDown(false);
}

// Minimal probe: 4 horizontal/vertical bones, each with one physics property and gravity 200 (see spines/<line>/probe.json).
// Prints the on-screen result (y down, + degrees = clockwise on screen, like Solar2D).
static void minimalProbe(const std::string &dir) {
    Loaded L = load("probe", "spineboy", dir + "/probe.json");
    float seen[3][4];  // per configuration: rotate angle, shearX angle, scaleX length, xy screen dy
    for (int ci = 0; ci < 3; ++ci) {
        Cfg c = (Cfg)ci;
        Rig rig(L.data);
        Skeleton &sk = *rig.sk; applyCfg(sk, c); spc::setToSetupPose(&sk); sk.updateWorldTransform(Physics_Reset);
        for (int f = 0; f < 60; ++f) { sk.update(1 / 60.f); sk.updateWorldTransform(Physics_Update); }
        float s = c == CR ? -1 : 1;  // world y -> screen y
        auto &rot = spc::applied(*sk.findBone("rot")), &sh = spc::applied(*sk.findBone("shear"));
        auto &sc = spc::applied(*sk.findBone("scale")), &xy = spc::applied(*sk.findBone("xy"));
        float rotDeg = std::atan2(rot.getC() * s, rot.getA()) * R2D;             // on-screen angle of the bone's x axis
        float shDeg = std::atan2(sh.getC() * s, sh.getA()) * R2D;
        float scaleLen = std::hypot(sc.getA(), sc.getC());                        // world scale of the bone's x axis (1 = rest)
        float xyDy = (xy.getWorldY() - 0) * s;
        seen[c][0] = rotDeg; seen[c][1] = shDeg; seen[c][2] = scaleLen; seen[c][3] = xyDy;
        std::printf("probe %s cfg %s (scaleY=%+.0f yDown=%d): rotate-bone angle %+7.2f deg (%s) | shearX-bone x-axis %+7.2f deg (%s) | "
                    "scaleX-bone (pointing up) length x%.4f (%s) | xy-bone screen dy %+8.2f (%s)\n",
                    g_variant.c_str(), cfgName[c], c == CA ? kPluginScaleY : 1.0f, Bone::isYDown(), rotDeg, rotDeg > 0 ? "droops DOWN" : "lifts UP", shDeg,
                    shDeg > 0 ? "droops DOWN" : "lifts UP", scaleLen, scaleLen < 1 ? "compressed by gravity" : "STRETCHED upward", xyDy,
                    xyDy > 0 ? "falls DOWN" : "rises UP");
    }
    Bone::setYDown(false);
    const char *bone[] = {"rotate", "shearX", "scaleX", "xy"};
    for (int k = 0; k < 4; ++k)
        check(std::fabs(seen[CA][k] - seen[CR][k]) < 1e-2 && std::fabs(seen[CB][k] - seen[CR][k]) < 1e-2, std::string("probe ") + bone[k]);
}

int main(int argc, char **argv) {
    g_variant = argc > 1 ? argv[1] : "?";
    if (getenv("YFLIP_PROBE")) { minimalProbe(getenv("YFLIP_PROBE")); return 0; }
    std::string detailPath = argc > 2 ? argv[2] : "/dev/null";
    g_detail = std::fopen(detailPath.c_str(), "w");
    const char *physSkels[] = {"celestial-circus", "cloud-pot", "sack", "snowglobe"};
    for (const char *n : physSkels) {
        Loaded L = load(n, n, std::string(n) + "/" + n + ".json");
        physicsSuite(L);
        directionProbe(L, g_detail);
    }
    // IK
    const char *W = getenv("YFLIP_SPINES");
    {
        Loaded L = load("spineboy", "spineboy", "spineboy/spineboy.json");
        runCase(L, ikScenario("ik crosshair +20,+20 (run+aim)", {"crosshair"}, {{0, "run"}, {1, "aim"}}, 60), false);
        runCase(L, ikScenario("ik all targets +20,+20 (setup)", ikTargets(L.data), {}, 30), false);
        runCase(L, ikScenario("ik all targets +20,+20 (run+aim)", ikTargets(L.data), {{0, "run"}, {1, "aim"}}, 60), false);
    }
    {
        Loaded L = load("raptor", "raptor", "raptor/raptor.json");
        runCase(L, ikScenario("ik leg targets +20,+20 (setup)", {"front-leg-target", "back-leg-target"}, {}, 30), false);
        runCase(L, ikScenario("ik leg targets +20,+20 (walk)", {"front-leg-target", "back-leg-target"}, {{0, "walk"}}, 60), false);
        runCase(L, ikScenario("ik all targets +20,+20 (walk)", ikTargets(L.data), {{0, "walk"}}, 60), false);
    }
    if (W) {
        for (const char *tag : {"ikOT", "ikNRR"}) {
            std::string nm = std::string("spineboy-") + tag;
            Loaded L = load(nm, "spineboy", std::string(W) + "/" + nm + ".json");
            runCase(L, ikScenario("ik 1-bone inherit crosshair (run+aim)", {"crosshair"}, {{0, "run"}, {1, "aim"}}, 60), false);
            runCase(L, ikScenario("ik 1-bone inherit all targets (setup)", ikTargets(L.data), {}, 30), false);
        }
    }
    // Sanity: every bundled skeleton, every animation (non-physics constraints: transform/path/IK), no user action
    if (getenv("YFLIP_ALL")) {
        const char *names[] = {"alien", "chibi-stickers", "coin", "goblins", "mix-and-match", "owl", "powerup", "raptor",
                               "speedy", "spineboy", "stretchyman", "tank", "vine", "windmill"};
        for (const char *n : names) {
            Loaded L = load(n, n, std::string(n) + "/" + n + ".json");
            Dev a, b;
            auto &anims = L.data->getAnimations();
            for (size_t i = 0; i < anims.size(); ++i) {
                std::string an = anims[i]->getName().buffer();
                Scenario sc; sc.name = "all-anims"; sc.frames = 120;
                sc.setup = [an](Skeleton &, AnimationState &st, Cfg) { st.setAnimation(0, an.c_str(), true); };
                Run r = simulate(L.data, CR, sc), ra = simulate(L.data, CA, sc), rb = simulate(L.data, CB, sc);
                std::vector<bool> all;
                a.merge(compare(r, ra, L.data, all)); b.merge(compare(r, rb, L.data, all));
            }
            Row row; row.skel = n; row.cas = "0 sanity: all anims x120 (no physics)"; row.A = a; row.B = b;
            g_rows.push_back(row);
            // IK targets for skeletons with IK
            bool hasIk = false;
            spc::forEachIkData(L.data, [&](auto *) { hasIk = true; });
            if (hasIk && anims.size())
                runCase(L, ikScenario("ik all targets +20,+20 (anim0)", ikTargets(L.data), {{0, anims[0]->getName().buffer()}}, 60), false);
        }
    }
    // summary table
    std::printf("%-8s %-16s %-40s | %-28s | %-28s\n", "variant", "skeleton", "case", "A (plugin): pos / rot deg", "B (yDown): pos / rot deg");
    for (auto &r : g_rows) {
        std::printf("%-8s %-16s %-40s | %11.4f / %9.4f    | %11.4f / %9.4f\n", g_variant.c_str(), r.skel.c_str(), r.cas.c_str(), r.A.pos, r.A.rot, r.B.pos, r.B.rot);
        for (auto &kv : r.groups)
            if (kv.second.first.pos > 1e-3 || kv.second.first.rot > 1e-3 || kv.second.second.pos > 1e-3 || kv.second.second.rot > 1e-3)
                std::printf("%-8s %-16s   %-38s | %11.4f / %9.4f    | %11.4f / %9.4f\n", "", "", ("group " + kv.first).c_str(), kv.second.first.pos,
                            kv.second.first.rot, kv.second.second.pos, kv.second.second.rot);
    }
    for (auto &r : g_rows) check(exact(r.A) && exact(r.B), "matrix " + r.skel + " " + r.cas);
    std::fclose(g_detail);
    return 0;
}
