// Y-flip fixture: the shared headless fixture (tests/host/realdata_fixture.cpp) plus a coordinate mode and bone
// readers, registered on the same require("realdata_fixture") module.
//   A = the plugin's configuration (plugin_config.cpp, generated by build.sh from the checkout)
//   B = skeleton scaleY=+1, Bone::setYDown(true)
//   R = skeleton scaleY=+1, y-up reference
#define luaopen_realdata_fixture realdata_fixture_base
#include "../host/realdata_fixture.cpp"
#undef luaopen_realdata_fixture

extern const float kPluginScaleY;
extern const bool kPluginYDown;

static char g_mode = 'A';

static Skeleton *skeletonOf(lua_State *L) {
    lua_getfield(L, 1, "_skeleton");
    return ((SpineSkeleton *)luaL_checkudata(L, -1, "SpineSkeleton"))->skeleton;
}

// fixture.setMode('A'|'B'|'R'): Bone::yDown now, skeleton scaleY for the next create()
static int setMode(lua_State *L) {
    g_mode = luaL_checkstring(L, 1)[0];
    Bone::setYDown(g_mode == 'B' || (g_mode == 'A' && kPluginYDown));
    return 0;
}

// fixture.create(dataHolder): the shared create() with the current mode's skeleton scaleY
static int createInMode(lua_State *L) {
    create(L);
    lua_getfield(L, -1, "_skeleton");
    ((SpineSkeleton *)lua_touserdata(L, -1))->skeleton->setScaleY(g_mode == 'A' ? kPluginScaleY : 1);
    lua_pop(L, 1);
    return 1;
}

// fixture.worldTransformPhysics(obj): skeleton:updateWorldTransform(Physics_Update), what updateState() does (draw() only poses: Physics_Pose)
static int worldTransformPhysics(lua_State *L) {
    skeletonOf(L)->updateWorldTransform(Physics_Update);
    return 0;
}

// fixture.boneWorld(obj, name) -> worldX, worldY
static int boneWorld(lua_State *L) {
    Bone *b = skeletonOf(L)->findBone(luaL_checkstring(L, 2));
    if (!b) return 0;
    auto &w = spc::applied(*b);
    lua_pushnumber(L, w.getWorldX()); lua_pushnumber(L, w.getWorldY());
    return 2;
}

// fixture.boneWorldFull(obj, name) -> worldX, worldY, worldRotationX
static int boneWorldFull(lua_State *L) {
    Bone *b = skeletonOf(L)->findBone(luaL_checkstring(L, 2));
    if (!b) return 0;
    auto &w = spc::applied(*b);
    lua_pushnumber(L, w.getWorldX()); lua_pushnumber(L, w.getWorldY()); lua_pushnumber(L, w.getWorldRotationX());
    return 3;
}

// fixture.boneNames(obj) -> { bone names in skeleton order }
static int boneNames(lua_State *L) {
    auto &bones = skeletonOf(L)->getBones();
    lua_newtable(L);
    for (size_t i = 0; i < bones.size(); ++i) { lua_pushstring(L, bones[i]->getData().getName().buffer()); lua_rawseti(L, -2, (int)i + 1); }
    return 1;
}

extern "C" int luaopen_realdata_fixture(lua_State *L) {
    realdata_fixture_base(L);
    const luaL_Reg fns[] = {{"setMode", setMode}, {"create", createInMode}, {"worldTransformPhysics", worldTransformPhysics},
                            {"boneWorld", boneWorld}, {"boneWorldFull", boneWorldFull}, {"boneNames", boneNames}, {NULL, NULL}};
    luaL_register(L, NULL, fns);
    return 1;
}
