local spine = require("plugin.spine")
local atlas = spine.loadAtlas("cloud-pot/cloud-pot.atlas")
local data = spine.loadSkeletonData("cloud-pot/cloud-pot.skel", atlas)
local obj = spine.create(data)
local physics = obj.physics
print("physics wrapper", physics)
obj:removeSelf(); __stub.frame(); collectgarbage(); collectgarbage()
print("after removeSelf")
__stub.raises("Physics constraint belongs to a removed skeleton", function() return physics.inertia end)
__stub.raises("Physics constraint belongs to a removed skeleton", function() physics:translate(1, 1) end)
print("survived")
