local spine = require("plugin.spine")
local S = __stub
local atlas = spine.loadAtlas("mix-and-match/mix-and-match.atlas")
local data = spine.loadSkeletonData("mix-and-match/mix-and-match.skel", atlas)
local a = spine.create(data)
local b = spine.create(data)
local sk = a:createSkin("outfit"); sk:addSkin("skin-base"); sk:addSkin("nose/short")
b:setSkin(sk); b:setSlotsToSetupPose(); b:draw()
sk = nil; S.gcfull()
a:removeSelf(); S.frame(); S.gcfull()
b:setAnimation(1, "walk", true); b:updateState(16); b:draw()
assert(b:getSkin().name == "outfit")
b:removeSelf(); S.frame(); a, b, data, atlas = nil, nil, nil, nil
S.gcfull()
print("shared custom skin lifecycle ok; textures released", S.texturesReleased, "of", S.texturesCreated)
